### PR TITLE
fix for npcraycastweaponbase

### PR DESCRIPTION
**Pull request by segabl**

### CODE REVIEW

**Comment by simon-wh** [comment]
There is custom code other than the 'NPCWeap:setup_weapon' that you removed from that function that is necessary

**Comment by antonpup** [comment]
From my experience, this mod still functions fine. I've seen people report crashes with raycastweaponbase, but I never encountered them and thus assumed that another mod is causing an issue for them.

But yeah, like Simon mentioned, you removed code that is needed. Such as the flashlight and laser pointer addons.

**Comment by segabl** [comment]
I didn't. The flashlight code is in the original function adn the thing I removed is:
`if NPCWeap.weapons[self._name_id] then
        local truee = true
        local falsee = false
        local object = self._unit:get_object(Idstring("g_attachment_peqbox"))
        if object then
            if object:visibility() == true then
            end
        end
    end`
which doesn't really do anything. And it's basically crashing because you fully overwrite the function but somewhere with the new updates a
`self._player_manager = managers.player`
got added into the init...

**Comment by GreatBigBushyBeard** [comment]
```lua
if self._multivoice then
        if not NPCRaycastWeaponBase._next_i_voice[self._name_id] then
            NPCRaycastWeaponBase._next_i_voice[self._name_id] = 1
        end
        self._voice = NPCRaycastWeaponBase._VOICES[NPCRaycastWeaponBase._next_i_voice[self._name_id]]
        if NPCRaycastWeaponBase._next_i_voice[self._name_id] == #NPCRaycastWeaponBase._VOICES then
            NPCRaycastWeaponBase._next_i_voice[self._name_id] = 1
        else
            NPCRaycastWeaponBase._next_i_voice[self._name_id] = NPCRaycastWeaponBase._next_i_voice[self._name_id] + 1
       end
    else
        self._voice = "a"
    end
```

**Comment by antonpup** [comment]
Well, my apologies then. I did not mean to come off rude.

I will look over this mod and your pr sometime in the next few days.

**Comment by segabl** [comment]
No problem, I know how it is like ^^

**Pull request closed without merging**
